databases:
  - name: expenso-db
    plan: free

services:
  - type: web
    name: expenso-backend
    env: ruby
    plan: free
    buildCommand: bundle install && bundle exec rails assets:precompile
    preDeployCommand: bundle exec rails db:migrate
    startCommand: bundle exec puma -C config/puma.rb
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_LOG_LEVEL
        value: info
      - key: APP_HOST
        sync: false
      - key: FRONTEND_ORIGINS
        sync: false
      - key: ACTIVE_STORAGE_SERVICE
        value: local
      - key: DATABASE_URL
        fromDatabase:
          name: expenso-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: SECRET_KEY_BASE
        sync: false

  - type: worker
    name: expenso-worker
    env: ruby
    plan: free
    buildCommand: bundle install
    startCommand: bin/jobs
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_LOG_LEVEL
        value: info
      - key: DATABASE_URL
        fromDatabase:
          name: expenso-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: SECRET_KEY_BASE
        sync: false
